# Generated by Django 3.0.1 on 2022-12-13 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='work',
        ),
        migrations.RemoveField(
            model_name='work',
            name='section_of_work',
        ),
        migrations.AddField(
            model_name='work',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='project_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='views',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='work',
            name='project_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Tag'),
        ),
        migrations.AddField(
            model_name='work',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Category'),
        ),
    ]
