# Generated by Django 3.0.1 on 2022-12-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20221213_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='software'),
            preserve_default=False,
        ),
    ]
