# Generated by Django 3.0.1 on 2023-01-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='project_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='work.Tag'),
        ),
        migrations.AlterField(
            model_name='work',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='work.Category'),
        ),
    ]
