# Generated by Django 3.0.1 on 2022-12-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_type', models.CharField(max_length=20)),
                ('numbers_of_comment', models.IntegerField()),
                ('date_published', models.DateField()),
                ('summary', models.CharField(max_length=120)),
            ],
        ),
    ]
