# Generated by Django 3.2.16 on 2022-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20221205_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='little_detail',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
