# Generated by Django 3.0.1 on 2022-12-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_degree', models.CharField(max_length=50)),
                ('name_of_institution', models.CharField(max_length=50)),
                ('year_started', models.DateField()),
                ('year_ended', models.DateField()),
            ],
        ),
    ]
