# Generated by Django 3.0.1 on 2022-12-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('country', models.CharField(max_length=50)),
                ('career', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=500)),
                ('biography_contd', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
