# Generated by Django 3.0.1 on 2022-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='service',
            field=models.CharField(choices=[('Graphics Design', 'Graphics Design'), ('Web Dev', 'Web Development'), ('Data Science', 'Data Science'), ('Full Stack', 'Full Stack')], default='Web Dev', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='service1',
            field=models.CharField(choices=[('Graphics Design', 'Graphics Design'), ('Web Dev', 'Web Development'), ('Data Science', 'Data Science'), ('Full Stack', 'Full Stack')], default='Graphiic Design', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='service2',
            field=models.CharField(choices=[('Graphics Design', 'Graphics Design'), ('Web Dev', 'Web Development'), ('Data Science', 'Data Science'), ('Full Stack', 'Full Stack')], default='Data Science', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='service3',
            field=models.CharField(choices=[('Graphics Design', 'Graphics Design'), ('Web Dev', 'Web Development'), ('Data Science', 'Data Science'), ('Full Stack', 'Full Stack')], default='Full Stack', max_length=50),
            preserve_default=False,
        ),
    ]
