# Generated by Django 3.0.1 on 2022-12-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('about', '0002_auto_20221204_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='service',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='service3',
        ),
        migrations.AddField(
            model_name='about',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
