# Generated by Django 3.2.16 on 2022-12-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20221205_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='field',
        ),
    ]
