# Generated by Django 3.0.1 on 2022-12-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_about_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
