# Generated by Django 3.0.1 on 2022-12-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50)),
                ('year_started', models.DateField()),
                ('year_ended_or_present', models.CharField(max_length=7)),
                ('summary', models.CharField(max_length=350)),
            ],
        ),
    ]
