# Generated by Django 3.0.1 on 2022-12-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year_started',
            field=models.CharField(max_length=4),
        ),
    ]
