# Generated by Django 3.2.16 on 2022-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skilL_grade',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_grade',
            field=models.CharField(default=80, max_length=2),
            preserve_default=False,
        ),
    ]
