# Generated by Django 3.2.16 on 2022-12-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20221206_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
