# Generated by Django 3.0.1 on 2022-12-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
